# Generated by Django 5.1.4 on 2025-02-05 21:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('capacidad', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='oficinas_fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='Suministro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='suministros/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])])),
            ],
        ),
        migrations.CreateModel(
            name='Reforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='reformas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])])),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('finalizado', models.BooleanField(default=False)),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofisina.contratista')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofisina.oficina')),
                ('suministros', models.ManyToManyField(to='ofisina.suministro')),
            ],
            options={
                'ordering': ['fecha_inicio', 'oficina'],
            },
        ),
    ]
